[0.195s] Invoking command in '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller': CMAKE_PREFIX_PATH=/home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller:/home/nwhit210/omnicar_2_ws/install/omnicar:/home/nwhit210/omnicar_2_ws/install/mecanum_drive_controller LD_LIBRARY_PATH=/home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller/lib:/home/nwhit210/omnicar_2_ws/install/mecanum_drive_controller/lib:/usr/lib/x86_64-linux-gnu/gazebo-11/plugins:/opt/ros/humble/opt/rviz_ogre_vendor/lib:/opt/ros/humble/lib/x86_64-linux-gnu:/opt/ros/humble/lib /usr/bin/ctest -C Release -D ExperimentalTest --no-compress-output -V --force-new-ctest-process
[0.206s] UpdateCTestConfiguration  from :/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/CTestConfiguration.ini
[0.206s] Parse Config file:/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/CTestConfiguration.ini
[0.206s]    Site: nwhit210
[0.206s]    Build name: (empty)
[0.206s]  Add coverage exclude regular expressions.
[0.206s] Create new tag: 20250318-0448 - Experimental
[0.206s] UpdateCTestConfiguration  from :/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/CTestConfiguration.ini
[0.206s] Parse Config file:/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/CTestConfiguration.ini
[0.206s] Test project /home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller
[0.207s] Constructing a list of tests
[0.207s] Done constructing a list of tests
[0.207s] Updating test list for fixtures
[0.207s] Added 0 tests to meet fixture requirements
[0.207s] Checking test dependency graph...
[0.207s] Checking test dependency graph end
[0.208s] test 1
[0.208s]     Start 1: example_2_urdf_xacro
[0.208s] 
[0.208s] 1: Test command: /usr/bin/python3 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/example_2_urdf_xacro.xunit.xml" "--package-name" "arduino_hardware_controller" "--output-file" "/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/example_2_urdf_xacro.txt" "--command" "/usr/bin/python3" "-u" "-m" "pytest" "/home/nwhit210/omnicar_2_ws/src/arduino_controller/test/test_urdf_xacro.py" "-o" "cache_dir=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/example_2_urdf_xacro/.cache" "--junit-xml=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/example_2_urdf_xacro.xunit.xml" "--junit-prefix=arduino_hardware_controller"
[0.208s] 1: Test timeout computed to be: 60
[0.287s] 1: -- run_test.py: invoking following command in '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller':
[0.287s] 1:  - /usr/bin/python3 -u -m pytest /home/nwhit210/omnicar_2_ws/src/arduino_controller/test/test_urdf_xacro.py -o cache_dir=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/example_2_urdf_xacro/.cache --junit-xml=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/example_2_urdf_xacro.xunit.xml --junit-prefix=arduino_hardware_controller
[0.794s] 1: ============================= test session starts ==============================
[0.795s] 1: platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
[0.803s] 1: cachedir: build/arduino_hardware_controller/ament_cmake_pytest/example_2_urdf_xacro/.cache
[0.803s] 1: rootdir: /home/nwhit210/omnicar_2_ws
[0.804s] 1: plugins: ament-xmllint-0.12.11, ament-pep257-0.12.11, ament-flake8-0.12.11, launch-testing-1.0.7, launch-testing-ros-0.19.8, ament-lint-0.12.11, ament-copyright-0.12.11, cov-3.0.0, colcon-core-0.19.0
[0.808s] 1: collected 1 item
[0.809s] 1: 
[1.023s] 1: ../../src/arduino_controller/test/test_urdf_xacro.py F                   [100%]
[1.023s] 1: 
[1.023s] 1: =================================== FAILURES ===================================
[1.023s] 1: _______________________________ test_urdf_xacro ________________________________
[1.023s] 1: 
[1.024s] 1:     def test_urdf_xacro():
[1.024s] 1:         # General Arguments
[1.024s] 1:         description_package = "arduino_hardware_controller"
[1.024s] 1:         description_file = "diffbot.urdf.xacro"
[1.024s] 1:     
[1.024s] 1:         description_file_path = os.path.join(
[1.024s] 1:             get_package_share_directory(description_package), "urdf", description_file
[1.024s] 1:         )
[1.025s] 1:     
[1.025s] 1:         (_, tmp_urdf_output_file) = tempfile.mkstemp(suffix=".urdf")
[1.025s] 1:     
[1.025s] 1:         # Compose `xacro` and `check_urdf` command
[1.025s] 1:         xacro_command = (
[1.025s] 1:             f"{shutil.which('xacro')}" f" {description_file_path}" f" > {tmp_urdf_output_file}"
[1.026s] 1:         )
[1.026s] 1:         check_urdf_command = f"{shutil.which('check_urdf')} {tmp_urdf_output_file}"
[1.026s] 1:     
[1.026s] 1:         # Try to call processes but finally remove the temp file
[1.026s] 1:         try:
[1.026s] 1:             xacro_process = subprocess.run(
[1.026s] 1:                 xacro_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True
[1.026s] 1:             )
[1.026s] 1:     
[1.026s] 1: >           assert xacro_process.returncode == 0, " --- XACRO command failed ---"
[1.026s] 1: E           AssertionError:  --- XACRO command failed ---
[1.026s] 1: E           assert 2 == 0
[1.027s] 1: E            +  where 2 = CompletedProcess(args='/opt/ros/humble/bin/xacro /home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller/share...nwhit210/omnicar_2_ws/install/arduino_hardware_controller/share/arduino_hardware_controller/urdf/diffbot.urdf.xacro\n').returncode
[1.027s] 1: 
[1.027s] 1: ../../src/arduino_controller/test/test_urdf_xacro.py:62: AssertionError
[1.027s] 1: - generated xml file: /home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/example_2_urdf_xacro.xunit.xml -
[1.027s] 1: =========================== short test summary info ============================
[1.027s] 1: FAILED ../../src/arduino_controller/test/test_urdf_xacro.py::test_urdf_xacro
[1.027s] 1: ============================== 1 failed in 0.23s ===============================
[1.098s] 1: -- run_test.py: return code 1
[1.098s] 1: -- run_test.py: verify result file '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/example_2_urdf_xacro.xunit.xml'
[1.111s] 1/3 Test #1: example_2_urdf_xacro .............***Failed    0.91 sec
[1.112s] test 2
[1.112s]     Start 2: view_example_2_launch
[1.112s] 
[1.112s] 2: Test command: /usr/bin/python3 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/view_example_2_launch.xunit.xml" "--package-name" "arduino_hardware_controller" "--output-file" "/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/view_example_2_launch.txt" "--command" "/usr/bin/python3" "-u" "-m" "pytest" "/home/nwhit210/omnicar_2_ws/src/arduino_controller/test/test_view_robot_launch.py" "-o" "cache_dir=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/view_example_2_launch/.cache" "--junit-xml=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/view_example_2_launch.xunit.xml" "--junit-prefix=arduino_hardware_controller"
[1.112s] 2: Test timeout computed to be: 60
[1.196s] 2: -- run_test.py: invoking following command in '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller':
[1.196s] 2:  - /usr/bin/python3 -u -m pytest /home/nwhit210/omnicar_2_ws/src/arduino_controller/test/test_view_robot_launch.py -o cache_dir=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/view_example_2_launch/.cache --junit-xml=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/view_example_2_launch.xunit.xml --junit-prefix=arduino_hardware_controller
[1.614s] 2: ============================= test session starts ==============================
[1.614s] 2: platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
[1.620s] 2: cachedir: build/arduino_hardware_controller/ament_cmake_pytest/view_example_2_launch/.cache
[1.621s] 2: rootdir: /home/nwhit210/omnicar_2_ws
[1.621s] 2: plugins: ament-xmllint-0.12.11, ament-pep257-0.12.11, ament-flake8-0.12.11, launch-testing-1.0.7, launch-testing-ros-0.19.8, ament-lint-0.12.11, ament-copyright-0.12.11, cov-3.0.0, colcon-core-0.19.0
[1.767s] 2: collected 1 item
[1.768s] 2: 
[1.971s] 2: ../../src/arduino_controller/test/test_view_robot_launch.py F            [100%]
[1.971s] 2: 
[1.971s] 2: =================================== FAILURES ===================================
[1.972s] 2: _____________________ launch tests: test_view_robot_launch _____________________
[1.972s] 2: 
[1.972s] 2: ----------------------------- Captured stdout call -----------------------------
[1.972s] 2: [INFO] [launch]: All log files can be found below /home/nwhit210/.ros/log/2025-03-18-14-48-39-727507-nwhit210-2717
[1.972s] 2: [INFO] [launch]: Default logging verbosity is set to INFO
[1.972s] 2: [ERROR] [launch]: Caught exception in launch (see debug for traceback): executed command failed. Command: /opt/ros/humble/bin/xacro /home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller/share/arduino_hardware_controller/urdf/diffbot.urdf.xacro prefix:=""
[1.973s] 2: Captured stderr output: error: package not found: "package 'ros2_control_demo_description' not found, searching: ['/home/nwhit210/omnicar_2_ws/install/omnicar', '/home/nwhit210/omnicar_2_ws/install/mecanum_drive_controller', '/home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller', '/opt/ros/humble']"
[1.973s] 2: when processing file: /home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller/share/arduino_hardware_controller/urdf/diffbot.urdf.xacro
[1.973s] 2: 
[1.973s] 2: Processes under test stopped before tests completed
[1.973s] 2: - generated xml file: /home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/view_example_2_launch.xunit.xml -
[1.973s] 2: =========================== short test summary info ============================
[1.973s] 2: FAILED ../../src/arduino_controller/test/test_view_robot_launch.py::test_view_robot_launch
[1.973s] 2: ============================== 1 failed in 0.36s ===============================
[2.055s] 2: -- run_test.py: return code 1
[2.055s] 2: -- run_test.py: verify result file '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/view_example_2_launch.xunit.xml'
[2.070s] 2/3 Test #2: view_example_2_launch ............***Failed    0.96 sec
[2.070s] test 3
[2.070s]     Start 3: run_example_2_launch
[2.070s] 
[2.070s] 3: Test command: /usr/bin/python3 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/run_example_2_launch.xunit.xml" "--package-name" "arduino_hardware_controller" "--output-file" "/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/run_example_2_launch.txt" "--command" "/usr/bin/python3" "-u" "-m" "pytest" "/home/nwhit210/omnicar_2_ws/src/arduino_controller/test/test_diffbot_launch.py" "-o" "cache_dir=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/run_example_2_launch/.cache" "--junit-xml=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/run_example_2_launch.xunit.xml" "--junit-prefix=arduino_hardware_controller"
[2.070s] 3: Test timeout computed to be: 60
[2.157s] 3: -- run_test.py: invoking following command in '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller':
[2.158s] 3:  - /usr/bin/python3 -u -m pytest /home/nwhit210/omnicar_2_ws/src/arduino_controller/test/test_diffbot_launch.py -o cache_dir=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/run_example_2_launch/.cache --junit-xml=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/run_example_2_launch.xunit.xml --junit-prefix=arduino_hardware_controller
[2.679s] 3: ============================= test session starts ==============================
[2.679s] 3: platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
[2.686s] 3: cachedir: build/arduino_hardware_controller/ament_cmake_pytest/run_example_2_launch/.cache
[2.686s] 3: rootdir: /home/nwhit210/omnicar_2_ws
[2.686s] 3: plugins: ament-xmllint-0.12.11, ament-pep257-0.12.11, ament-flake8-0.12.11, launch-testing-1.0.7, launch-testing-ros-0.19.8, ament-lint-0.12.11, ament-copyright-0.12.11, cov-3.0.0, colcon-core-0.19.0
[2.905s] 3: collected 0 items / 1 error
[2.960s] 3: 
[2.961s] 3: ==================================== ERRORS ====================================
[2.961s] 3: ________________________ ERROR collecting test session _________________________
[2.961s] 3: /usr/lib/python3/dist-packages/pluggy/hooks.py:286: in __call__
[2.961s] 3:     return self._hookexec(self, self.get_hookimpls(), kwargs)
[2.961s] 3: /usr/lib/python3/dist-packages/pluggy/manager.py:92: in _hookexec
[2.962s] 3:     return self._inner_hookexec(hook, methods, kwargs)
[2.962s] 3: /usr/lib/python3/dist-packages/pluggy/manager.py:83: in <lambda>
[2.963s] 3:     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
[2.963s] 3: /usr/lib/python3/dist-packages/_pytest/python.py:200: in pytest_collect_file
[2.963s] 3:     module: Module = ihook.pytest_pycollect_makemodule(path=path, parent=parent)
[2.963s] 3: /usr/lib/python3/dist-packages/pluggy/hooks.py:286: in __call__
[2.963s] 3:     return self._hookexec(self, self.get_hookimpls(), kwargs)
[2.964s] 3: /usr/lib/python3/dist-packages/pluggy/manager.py:92: in _hookexec
[2.964s] 3:     return self._inner_hookexec(hook, methods, kwargs)
[2.964s] 3: /usr/lib/python3/dist-packages/pluggy/manager.py:83: in <lambda>
[2.964s] 3:     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
[2.964s] 3: /opt/ros/humble/lib/python3.10/site-packages/launch_testing/pytest/hooks.py:193: in pytest_pycollect_makemodule
[2.964s] 3:     entrypoint = find_launch_test_entrypoint(path)
[2.964s] 3: /opt/ros/humble/lib/python3.10/site-packages/launch_testing/pytest/hooks.py:186: in find_launch_test_entrypoint
[2.964s] 3:     module = path.pyimport()
[2.964s] 3: /usr/lib/python3/dist-packages/py/_path/local.py:704: in pyimport
[2.964s] 3:     __import__(modname)
[2.964s] 3: /usr/lib/python3/dist-packages/_pytest/assertion/rewrite.py:170: in exec_module
[2.965s] 3:     exec(co, module.__dict__)
[2.965s] 3: ../../src/arduino_controller/test/test_diffbot_launch.py:43: in <module>
[2.965s] 3:     from ros2_control_demo_testing.test_utils import (
[2.965s] 3: E   ModuleNotFoundError: No module named 'ros2_control_demo_testing'
[2.965s] 3: - generated xml file: /home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/run_example_2_launch.xunit.xml -
[2.965s] 3: =========================== short test summary info ============================
[2.965s] 3: ERROR ../.. - ModuleNotFoundError: No module named 'ros2_control_demo_testing'
[2.965s] 3: !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
[2.965s] 3: =============================== 1 error in 0.28s ===============================
[3.062s] 3: -- run_test.py: return code 2
[3.067s] 3: -- run_test.py: verify result file '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/run_example_2_launch.xunit.xml'
[3.079s] 3/3 Test #3: run_example_2_launch .............***Failed    1.01 sec
[3.080s] 
[3.081s] 0% tests passed[0;0m, [0;31m3 tests failed[0;0m out of 3
[3.081s] 
[3.081s] Label Time Summary:
[3.081s] pytest    =   2.87 sec*proc (3 tests)
[3.081s] 
[3.082s] Total Test time (real) =   2.88 sec
[3.082s] 
[3.082s] The following tests FAILED:
[3.082s] 	[0;31m  1 - example_2_urdf_xacro (Failed)[0;0m
[3.082s] 	[0;31m  2 - view_example_2_launch (Failed)[0;0m
[3.082s] 	[0;31m  3 - run_example_2_launch (Failed)[0;0m
[3.083s] Errors while running CTest
[3.083s] Output from these tests are in: /home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/Testing/Temporary/LastTest.log
[3.084s] Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
[3.088s] Invoked command in '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller' returned '8': CMAKE_PREFIX_PATH=/home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller:/home/nwhit210/omnicar_2_ws/install/omnicar:/home/nwhit210/omnicar_2_ws/install/mecanum_drive_controller LD_LIBRARY_PATH=/home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller/lib:/home/nwhit210/omnicar_2_ws/install/mecanum_drive_controller/lib:/usr/lib/x86_64-linux-gnu/gazebo-11/plugins:/opt/ros/humble/opt/rviz_ogre_vendor/lib:/opt/ros/humble/lib/x86_64-linux-gnu:/opt/ros/humble/lib /usr/bin/ctest -C Release -D ExperimentalTest --no-compress-output -V --force-new-ctest-process
