-- run_test.py: invoking following command in '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller':
 - /usr/bin/python3 -u -m pytest /home/nwhit210/omnicar_2_ws/src/arduino_controller/test/test_view_robot_launch.py -o cache_dir=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/view_example_2_launch/.cache --junit-xml=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/view_example_2_launch.xunit.xml --junit-prefix=arduino_hardware_controller

============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: build/arduino_hardware_controller/ament_cmake_pytest/view_example_2_launch/.cache
rootdir: /home/nwhit210/omnicar_2_ws
plugins: ament-xmllint-0.12.11, ament-pep257-0.12.11, ament-flake8-0.12.11, launch-testing-1.0.7, launch-testing-ros-0.19.8, ament-lint-0.12.11, ament-copyright-0.12.11, cov-3.0.0, colcon-core-0.19.0
collected 1 item

../../src/arduino_controller/test/test_view_robot_launch.py F            [100%]

=================================== FAILURES ===================================
_____________________ launch tests: test_view_robot_launch _____________________

----------------------------- Captured stdout call -----------------------------
[INFO] [launch]: All log files can be found below /home/nwhit210/.ros/log/2025-03-18-14-48-39-727507-nwhit210-2717
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executed command failed. Command: /opt/ros/humble/bin/xacro /home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller/share/arduino_hardware_controller/urdf/diffbot.urdf.xacro prefix:=""
Captured stderr output: error: package not found: "package 'ros2_control_demo_description' not found, searching: ['/home/nwhit210/omnicar_2_ws/install/omnicar', '/home/nwhit210/omnicar_2_ws/install/mecanum_drive_controller', '/home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller', '/opt/ros/humble']"
when processing file: /home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller/share/arduino_hardware_controller/urdf/diffbot.urdf.xacro

Processes under test stopped before tests completed
- generated xml file: /home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/view_example_2_launch.xunit.xml -
=========================== short test summary info ============================
FAILED ../../src/arduino_controller/test/test_view_robot_launch.py::test_view_robot_launch
============================== 1 failed in 0.36s ===============================


-- run_test.py: return code 1
-- run_test.py: verify result file '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/view_example_2_launch.xunit.xml'
